-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.admission_source
(
    admission_source_id integer NOT NULL,
    description character varying(80) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT pk_admission_source PRIMARY KEY (admission_source_id)
);

CREATE TABLE IF NOT EXISTS public.admission_type
(
    admission_type_id integer NOT NULL,
    description character varying(80) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT pk_admission_type PRIMARY KEY (admission_type_id)
);

CREATE TABLE IF NOT EXISTS public.diagnosis_table
(
    diag_number integer NOT NULL,
    diagnosis_code character varying(15) COLLATE pg_catalog."default" NOT NULL,
    diagnosis_name character varying(200) COLLATE pg_catalog."default",
    CONSTRAINT diagnosis_table_pkey PRIMARY KEY (diag_number)
);

CREATE TABLE IF NOT EXISTS public.discharge
(
    discharge_disposition_id integer NOT NULL,
    description character varying(110) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT pk_discharge PRIMARY KEY (discharge_disposition_id)
);

CREATE TABLE IF NOT EXISTS public.encounter_table
(
    encounter_id integer NOT NULL,
    patient_nbr integer NOT NULL,
    admission_type_id integer NOT NULL,
    admission_source_id integer NOT NULL,
    discharge_disposition_id integer NOT NULL,
    time_in_hospital integer NOT NULL,
    num_lab_procedures integer NOT NULL,
    num_procedures integer NOT NULL,
    num_medications integer NOT NULL,
    number_emergency integer NOT NULL,
    number_outpatient integer NOT NULL,
    number_inpatient integer NOT NULL,
    diag_1 character varying(80) COLLATE pg_catalog."default" NOT NULL,
    diag_2 character varying(80) COLLATE pg_catalog."default" NOT NULL,
    diag_3 character varying(80) COLLATE pg_catalog."default" NOT NULL,
    number_diagnosis integer NOT NULL,
    max_glu_serum character varying(80) COLLATE pg_catalog."default" NOT NULL,
    "A1Cresult" character varying(80) COLLATE pg_catalog."default" NOT NULL,
    change character varying(80) COLLATE pg_catalog."default" NOT NULL,
    "diabtesMed" character varying(80) COLLATE pg_catalog."default" NOT NULL,
    readmitted character varying(80) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT pk_encounter_table PRIMARY KEY (encounter_id)
);

CREATE TABLE IF NOT EXISTS public.medication_table
(
    medication_id integer NOT NULL,
    medication_type character varying(80) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT pk_medication_table PRIMARY KEY (medication_id)
);

CREATE TABLE IF NOT EXISTS public.patient_medication_table
(
    encounter_id integer NOT NULL,
    medication_id integer NOT NULL,
    change_in_dosage character varying(80) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT pk_medication_encounter_id PRIMARY KEY (medication_id, encounter_id)
);

CREATE TABLE IF NOT EXISTS public.patients
(
    patient_nbr integer NOT NULL,
    age character varying(80) COLLATE pg_catalog."default" NOT NULL,
    race character varying(80) COLLATE pg_catalog."default" NOT NULL,
    gender character varying(80) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT pk_patients PRIMARY KEY (patient_nbr)
);

ALTER TABLE IF EXISTS public.patient_medication_table
    ADD CONSTRAINT patient_medication_table_encounter_id_fkey FOREIGN KEY (encounter_id)
    REFERENCES public.encounter_table (encounter_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.patient_medication_table
    ADD CONSTRAINT patient_medication_table_medication_id_fkey FOREIGN KEY (medication_id)
    REFERENCES public.medication_table (medication_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;